language: python
python: 3.5
env:
- TOXENV=py27
- TOXENV=pypy
install:
- pip install -U tox
- pip install -r requirements_travis.txt
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: kintoandar
  password:
    secure: XyYzrWWDmOygMaE5KwgE4OyiWyWpTvHFo6mK01eRF3d9EQThpvKb4HoGCkQT8MkN2kFfvUYZiLtW/rfCIjkgzJxC1Q/I1Ln7D3fYk7HRt6qbgmv5edlUNhnicun8GNwLaBZugfmM95ZtHLHKB6hcxHwQVY2dxLUZBxlJQIL/AZoCf8YtkiO4ctA/EzhRil18Rt9X3rEw7kY1FMeAfpVF4kJiP0jQJhqF5704+CxbbNlQ9NoZl6tFm4bAQAx0RKrmF0qq6u90lfEkVYyrTDOX8UIEPk6/c9ieGT4/W/QzTzBFckGBX1O9K40x52K7CbgKg1QSmePuN0blQMCqtACPBkMuAAz+vVjSQHJhDTC4cVUE4BqK1ElsDvf6vl9ayc4kCzOzCMXRcHs46V/QsUExiSKFmTKoq2fD6HSEwbJyevSCZW+ec4LGkaumakXnKEkhZ4QiQ66lm4t68Io0RADgDuHmVdGTDDohRqMtoSgp4u2nJl/6C/KyWIMz+O4+rLKQ3P5JRXxOtJWtsKjSS1vFnwo5cQFc6RQO+TbSNx4tgtfNg0w0Opfkal/wpxEp/Zfw0gq0PBGxdYGUImpz82ZTEXBNQi+6pwNtpSisitgKth28+G/k2PepqN71fJVq0eCNed7kTQ8grtwLubZSQfyVkXkqDkDJ3caEIOhmFge4VHA=
  on:
    tags: true
    repo: kintoandar/snooper
    condition: "$TOXENV == py27"
